sudo: false
language: c
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
     - libfcgi-dev
     - valgrind
     - nginx
     - spawn-fcgi
before_install:
  - sudo apt-get update -qq
before_script:
  - s/travis-build
script:
  - s/build
  - s/runtests
os:
  - linux
  - osx
